# test_pdf.py - Test PDF generation separately
import streamlit as st
from fpdf import FPDF

st.title("PDF Generation Test")

if st.button("Generate Test PDF"):
    # Create a simple PDF
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt="Legal Assistant POC - Test Document", ln=1, align='C')
    pdf.cell(200, 10, txt="This is a test PDF document.", ln=1)
    pdf.cell(200, 10, txt="Generated by Legal AI Assistant", ln=1)
    
    # Convert to bytes for download
    pdf_bytes = pdf.output(dest='S').encode('latin1')
    
    # Download button
    st.download_button(
        "Download Test PDF",
        data=pdf_bytes,
        file_name="test_document.pdf",
        mime="application/pdf"
    )
    st.success("PDF generated successfully!")



    